// Owner: Reader (Ahana).
//
// TEMP: stands in for Encryption/Download's download pass, which is what will
// call ContentStore.store() in production. Without something storing a package
// first, openSession() throws DECRYPTION_FAILED and getBook() can never resolve.
//
// Delete this file when the real download pass lands, then drop the ensureSeeded()
// call in readerAssets.ts.
//
// NOTE assets/reader/sample-plaintext.epub is NO LONGER this file's to delete with
// it — Search's extractor hard-codes that path, so it is now a shared fixture and its
// removal needs Search looped in separately.
//
// What DOES go with this file: the dev search index, which is five items spanning a
// script, an asset and two manifests. The full list is in the header of
// src/features/reader/scripts/buildSampleSearchIndex.ts — read it before deleting,
// or you will leave a dangling script and a stale 360 KB asset behind.

import { Asset } from 'expo-asset';
import { File, Paths } from 'expo-file-system';
import { randomBytes } from 'react-native-quick-crypto';

import { encrypt } from '@/features/encryption/aesGcm';
import { contentStore } from '@/features/encryption/contentStore';
import {
  generateDeviceKeypair,
  publicKeyFingerprint,
  wrapBek,
} from '@/features/encryption/deviceKeypair';
import { utf8Encode } from '@/features/encryption/utf8';
import type { BookId, ContentFormat, EncryptedPackage, SignedLicence } from '@/shared/contracts';

/* eslint-disable-next-line @typescript-eslint/no-require-imports -- Metro asset handle; `.epub` resolves via metro.config.js assetExts. */
const SAMPLE_EPUB_MODULE = require('../../../assets/reader/sample-plaintext.epub') as number;

/**
 * TEMP, with the rest of this file — see the header for the full deletion list.
 *
 * ONE INDEX PER FORMAT, and they are not interchangeable: `queryBookIndex` throws outright when an
 * index's `bookId` is not the book that was asked for, so attaching the EPUB's index to a PDF book
 * turns every search into an ERROR rather than an empty list. That is why the PDF fixture carried no
 * index at all until its own was generated, and why a PDF search returned [] forever and looked like
 * an unimplemented feature. Search's PDF extractor had been working the whole time.
 *
 * Generated by `npm run reader:build-sample-index`. Required as objects rather than file reads: Metro
 * inlines `.json` at bundle time, so these need no expo-asset round trip the way the `.epub` does.
 */
const SAMPLE_EPUB_SEARCH_INDEX = require('../../../assets/reader/sample-search-index.json') as unknown;
const SAMPLE_PDF_SEARCH_INDEX =
  require('../../../assets/reader/sample-pdf-search-index.json') as unknown;

/**
 * TEMP, with the rest of this file. Generated by `npm run reader:build-sample-pdf`.
 *
 * A LARGE REAL PDF DOES NOT BELONG HERE, and the mechanism for one already exists: set
 * EXPO_PUBLIC_READER_FIXTURE_PATH with EXPO_PUBLIC_READER_FORMAT=PDF and the bytes come from a book
 * pushed into the app container, under its own bookId, with no tracked file touched. A swapped
 * `require()` cannot do that safely — Metro resolves it statically, so an untracked asset is a hard
 * bundling error for everyone who does not have that exact file on disk, and the generated
 * placeholder is the CI-checked, byte-reproducible fixture this path is supposed to seed.
 *
 * Needs no metro.config.js entry: `.pdf` is already in Expo's default assetExts (only
 * `.epub` had to be added). Resolved through expo-asset exactly like the EPUB.
 */
const SAMPLE_PDF_MODULE = require('../../../assets/reader/sample-plaintext.pdf') as number;

/**
 * TEMP, with the rest of this file. Generated by `npm run reader:build-sample-audio`
 * (`scripts/generateSampleAudio.ts`) — see that script's header for why WAV rather than a
 * compressed format.
 *
 * UNLIKE THE EPUB/PDF FIXTURES ABOVE, this one seeds through `buildAudioPackage` below, not
 * `buildPackage` — audio is never encrypted (primitives.ts, content-provider.ts), so there is no
 * BEK/wrap step to run for it at all.
 *
 * Also needs no metro.config.js entry: `.wav` is already in Expo's default assetExts.
 */
const SAMPLE_AUDIO_MODULE = require('../../../assets/reader/sample-plaintext.wav') as number;

const EPUB_MIME_TYPE = 'application/epub+zip';
const PDF_MIME_TYPE = 'application/pdf';
const AUDIO_MIME_TYPE = 'audio/wav';

/** AES-256. Mirrors KEY_BYTES in aesGcm.ts and BEK_BYTES in deviceKeypair.ts. */
const BEK_BYTES = 32;

/**
 * Absolute paths to large books pushed into the app container, used INSTEAD of the bundled samples.
 * Measurement scaffolding for the whole-book work — unset in every normal run.
 *
 * ONE PATH PER FORMAT, so both large books are reachable in the SAME run. That is what lets the
 * picker in App.tsx offer four tabs at once instead of two; with a single path crossed against
 * DEV_FORMAT (the shape this had until 2026-08-20) only one large book existed per bundle, and
 * comparing the two meant restarting Metro with a different env var.
 *
 * `EXPO_PUBLIC_READER_FIXTURE_PATH` is kept as a fallback for whichever format DEV_FORMAT selects,
 * so the single-var measurement runs already written down in READER_MEASUREMENTS.md keep working
 * unchanged. Prefer the per-format vars in anything new.
 *
 * WHY A PATH AND NOT A BUNDLED ASSET: Metro resolves require() statically at bundle time, so a
 * gitignored 20 MB asset is a hard bundling error rather than a soft miss — a "guarded require" is
 * not possible. And a real book must never be committed (T4_Readme.md: never commit real content,
 * encrypted or not). Reading an absolute path sidesteps Metro entirely, which is the same thing
 * sampleBookBytes() already does once expo-asset has resolved a URI.
 *
 * LITERAL MEMBER ACCESS, deliberately — see readerTiming.ts's isTimingEnabled() for why a computed
 * process.env lookup silently never gets inlined.
 *
 * >>> THIS PUTS PLAINTEXT IN THE APP CONTAINER BY CONSTRUCTION. <<< The file is an unencrypted
 * book sitting on disk until it is deleted, which is exactly what a storage-leak sweep should flag.
 * Delete it once the ciphertext is stored and BEFORE running any forensic sweep, or the sweep
 * either reports your own fixture as a leak or "passes" while real content sits in the container.
 */
const FIXTURE_PATH = process.env.EXPO_PUBLIC_READER_FIXTURE_PATH;
const FIXTURE_EPUB_PATH = process.env.EXPO_PUBLIC_READER_FIXTURE_EPUB;
const FIXTURE_PDF_PATH = process.env.EXPO_PUBLIC_READER_FIXTURE_PDF;

/**
 * Which renderer to exercise on this run. `EXPO_PUBLIC_READER_FORMAT=PDF` seeds the sample PDF
 * instead of the sample EPUB, which is the only way to reach the pdf.js path on a device before
 * there is a library screen to pick a real book from.
 *
 * EPUB unless PDF is asked for EXACTLY: anything else — a typo, 'pdf', 'AUDIO' — falls back rather
 * than seeding a book with a format nothing can open. AUDIO is not a launch-default option here —
 * this var only ever picks EPUB or PDF — but an audio fixture DOES now exist
 * (`DEV_SAMPLE_AUDIO_BOOK_ID`, seeded via `buildAudioPackage`, reachable from `BookListScreen`
 * directly): opening it still hits the reader's UNSUPPORTED_FORMAT refusal, since no AUDIO
 * renderer/route exists yet (AUDIO_PHASE0_FINDINGS.md, Phase 4).
 *
 * ONLY CHOOSES THE LAUNCH DEFAULT NOW, not which books exist. All four fixtures are seeded on
 * demand and all four are offered as tabs, so this decides which one is open before the first tap
 * — it is no longer the only way to reach the pdf.js path, just the fastest.
 *
 * LITERAL MEMBER ACCESS, deliberately — same reason as FIXTURE_PATH above.
 */
const DEV_FORMAT: ContentFormat = process.env.EXPO_PUBLIC_READER_FORMAT === 'PDF' ? 'PDF' : 'EPUB';

/**
 * Each large fixture's source path: its own var, or the legacy shared one when DEV_FORMAT names
 * this format. The per-format var wins, so setting both is not ambiguous.
 *
 * `undefined` means "no large book of this format was pushed", which is the normal case and is NOT
 * an error here — the tab still appears in App.tsx's picker, and the failure is raised only if it
 * is actually tapped (see sampleBookBytes). Hiding the tab instead would make a mis-set env var
 * look like a missing feature.
 */
const EPUB_FIXTURE_PATH = FIXTURE_EPUB_PATH ?? (DEV_FORMAT === 'EPUB' ? FIXTURE_PATH : undefined);
const PDF_FIXTURE_PATH = FIXTURE_PDF_PATH ?? (DEV_FORMAT === 'PDF' ? FIXTURE_PATH : undefined);

/**
 * A DISTINCT id per fixture, and not cosmetic: ensureSeeded() short-circuits on
 * isAvailableOffline(), so a shared id would find whatever was stored first and never seed the
 * other. With the large EPUB that meant measuring the 3.6 KB book and believing it was 20 MB; with
 * the PDF it would mean `getFormat()` reporting EPUB for a book you asked to be a PDF, and the
 * reader dutifully loading the epub.js shell for it.
 */
export const DEV_SAMPLE_EPUB_BOOK_ID: BookId = 'dev-sample-epub';
export const DEV_SAMPLE_PDF_BOOK_ID: BookId = 'dev-sample-pdf';
export const DEV_FIXTURE_EPUB_BOOK_ID: BookId = 'dev-fixture-epub';
export const DEV_FIXTURE_PDF_BOOK_ID: BookId = 'dev-fixture-pdf';
/**
 * AUDIO PHASE 1 — see AUDIO_PHASE0_FINDINGS.md. No "big pushed fixture" counterpart exists for
 * this one yet (unlike EPUB/PDF's `DEV_FIXTURE_*` ids) — a real-sized audio measurement fixture
 * is not this phase's job.
 */
export const DEV_SAMPLE_AUDIO_BOOK_ID: BookId = 'dev-sample-audio';
/**
 * Same bundled WAV as DEV_SAMPLE_AUDIO_BOOK_ID, seeded ENCRYPTED instead — see this file's
 * `audioEncrypted` fixture flag. A distinct id, not a flag on the existing one, for the same
 * reason every other fixture here gets its own id: two different packages must never share a
 * cache key.
 */
export const DEV_SAMPLE_AUDIO_ENCRYPTED_BOOK_ID: BookId = 'dev-sample-audio-encrypted';

/**
 * The book App.tsx opens on launch, when nothing has been picked yet — the DEFAULT only. Every
 * fixture is reachable from the picker regardless of what this resolves to, which is the difference
 * from the version of this file that crossed one shared path against DEV_FORMAT.
 *
 * PREFERS THE LARGE BOOK OF THE SELECTED FORMAT when one was pushed, because someone who set a
 * fixture path asked for that book; the bundled stand-in is the fallback, not the other way round.
 * Each combination still lands on its own id so none can be served a package seeded for another —
 * see the distinct-id note above for why that matters more than it looks.
 */
export const DEV_SAMPLE_BOOK_ID: BookId =
  DEV_FORMAT === 'PDF'
    ? (PDF_FIXTURE_PATH ? DEV_FIXTURE_PDF_BOOK_ID : DEV_SAMPLE_PDF_BOOK_ID)
    : (EPUB_FIXTURE_PATH ? DEV_FIXTURE_EPUB_BOOK_ID : DEV_SAMPLE_EPUB_BOOK_ID);

interface DevFixture {
  format: ContentFormat;
  mimeType: string;
  /** null ⇒ read from `fixturePath` instead of a bundled asset. */
  assetModule: number | null;
  /**
   * Where a non-bundled fixture's bytes come from, and `undefined` when nothing was pushed for it.
   *
   * PER FIXTURE, not one module-level path, because both large books are offered at once now — a
   * shared path would hand the PDF tab an EPUB's bytes the moment only one var was set, and store
   * them under `format: 'PDF'`. That is the exact defect devFixturePath.test.ts already pins for
   * the source/format crossing, one level down.
   */
  fixturePath?: string;
  name: string;
  /**
   * The index to encrypt alongside the content, or null for a book that has none.
   *
   * WAS A BOOLEAN, and that was the bug's hiding place: with only one index in the repo, "attach it?"
   * and "which one?" looked like the same question, so the PDF fixtures answered `false` and stayed
   * unsearchable. Naming the index makes a fixture with no index a deliberate null rather than a
   * default.
   */
  searchIndex: unknown | null;
  /**
   * AUDIO only. Default (undefined/false) keeps `buildAudioPackage`'s plaintext-only path — see
   * that function's own doc comment for why audio is unencrypted by default. `true` routes this
   * fixture through `buildPackage()` instead (the same real on-device RSA-OAEP + AES-GCM encrypt
   * every other format uses), overriding that default for this one bookId. See
   * `content-provider.ts`'s `EncryptedPackage.encryption` comment for why that override exists.
   */
  audioEncrypted?: boolean;
}

/**
 * EVERYTHING FIXTURE-SPECIFIC, KEYED BY bookId — and the keying is the point.
 *
 * This used to read a module-level `DEV_FORMAT` derived from an env var, which meant
 * the format was fixed for the whole bundle and could only change with a restart. It
 * is now a property of WHICH BOOK you asked for, which is both what production does
 * (the format arrives with the downloaded package) and what lets the reader switch
 * formats at runtime with no change to the routing logic: `ensureSeeded(bookId)`
 * stores the right format, `getFormat(bookId)` reads it back, and the reader picks its
 * shell from that. The env var now only chooses the DEFAULT book, not the capability.
 */
const DEV_FIXTURES: Readonly<Record<string, DevFixture>> = {
  [DEV_SAMPLE_EPUB_BOOK_ID]: {
    format: 'EPUB',
    mimeType: EPUB_MIME_TYPE,
    assetModule: SAMPLE_EPUB_MODULE,
    name: 'sample-plaintext.epub',
    searchIndex: SAMPLE_EPUB_SEARCH_INDEX,
  },
  [DEV_SAMPLE_PDF_BOOK_ID]: {
    format: 'PDF',
    mimeType: PDF_MIME_TYPE,
    assetModule: SAMPLE_PDF_MODULE,
    name: 'sample-plaintext.pdf',
    // Its OWN index, built by the same extractor -> buildIndex -> queryIndex pipeline the EPUB uses.
    // The locators are `{type:'PDF', page, offset}`, which the reader now resolves through
    // `goTo({kind:'page'})`.
    searchIndex: SAMPLE_PDF_SEARCH_INDEX,
  },
  [DEV_FIXTURE_EPUB_BOOK_ID]: {
    format: 'EPUB',
    mimeType: EPUB_MIME_TYPE,
    assetModule: null,
    fixturePath: EPUB_FIXTURE_PATH,
    name: 'the pushed large EPUB',
    // A different EPUB under a different bookId: the sample index's CFIs address the wrong book, and
    // no index exists for whatever book is pushed in, so search correctly returns [].
    searchIndex: null,
  },
  [DEV_FIXTURE_PDF_BOOK_ID]: {
    format: 'PDF',
    mimeType: PDF_MIME_TYPE,
    assetModule: null,
    fixturePath: PDF_FIXTURE_PATH,
    name: 'the pushed large PDF',
    // No index exists for a book pushed in at measurement time, so search returns []. Building one on
    // device would mean running the extractor in the RN bundle, which is what the scripts/ split
    // exists to avoid.
    searchIndex: null,
  },
  [DEV_SAMPLE_AUDIO_BOOK_ID]: {
    format: 'AUDIO',
    mimeType: AUDIO_MIME_TYPE,
    assetModule: SAMPLE_AUDIO_MODULE,
    name: 'sample-plaintext.wav',
    // search.ts's BookSearchIndex.format excludes AUDIO outright — no index exists for this
    // format, on any book, ever. Not "not built yet" the way the PDF fixtures' null once was.
    searchIndex: null,
  },
  [DEV_SAMPLE_AUDIO_ENCRYPTED_BOOK_ID]: {
    format: 'AUDIO',
    mimeType: AUDIO_MIME_TYPE,
    assetModule: SAMPLE_AUDIO_MODULE,
    name: 'sample-plaintext.wav (encrypted)',
    searchIndex: null,
    audioEncrypted: true,
  },
};

function fixtureFor(bookId: BookId): DevFixture {
  const fixture = DEV_FIXTURES[bookId];
  if (!fixture) {
    throw new Error(
      `devContentSeed has no fixture for bookId "${bookId}". This file only stands in for ` +
        `Download's real pass, so it can only seed the ids it knows: ` +
        `${Object.keys(DEV_FIXTURES).join(', ')}.`,
    );
  }
  return fixture;
}

async function sampleBookBytes(bookId: BookId): Promise<Uint8Array> {
  const { assetModule, fixturePath, name, format } = fixtureFor(bookId);

  if (assetModule === null) {
    // NAMES THE VARIABLE THAT WOULD FIX IT. These two are offered as tabs whether or not anything
    // was pushed for them (see EPUB_FIXTURE_PATH's comment), so this message is the ONLY place a
    // tap on an unpopulated tab explains itself — it surfaces in ReaderScreen's error banner.
    const envVar = format === 'PDF' ? 'EXPO_PUBLIC_READER_FIXTURE_PDF' : 'EXPO_PUBLIC_READER_FIXTURE_EPUB';
    // Points at samples/fixtures/ (gitignored) rather than the app container deliberately: both
    // are readable, but a container copy leaves an unencrypted book in the app's own Documents
    // directory, which is what a storage-leak sweep is meant to catch. Same guidance as CLAUDE.md.
    const pushHint =
      `Put one in samples/fixtures/ and restart Metro with ` +
      `${envVar}="$PWD/samples/fixtures/<book>" npx expo start --dev-client --clear ` +
      `(--clear is required: EXPO_PUBLIC_* is inlined at transform time).`;

    if (!fixturePath) {
      throw new Error(
        `No large ${format} is configured: ${envVar} is not set (nor is ` +
          `EXPO_PUBLIC_READER_FIXTURE_PATH with EXPO_PUBLIC_READER_FORMAT=${format}). ${pushHint}`
      );
    }
    const fixture = new File(fixturePath);
    if (!fixture.exists) {
      throw new Error(
        `${envVar} is set to "${fixturePath}" but no file is there. ${pushHint} ` +
          `The file must be a ${format}, which is the format this tab seeds it as.`
      );
    }
    return fixture.bytesSync();
  }

  const asset = Asset.fromModule(assetModule);

  // Not a network call for a bundled asset, but required: without it `localUri`
  // is null in dev, the classic "works in release, blank in dev" split.
  await asset.downloadAsync();

  const uri = asset.localUri ?? asset.uri;
  if (!uri) {
    throw new Error(`Could not resolve a local URI for ${name}.`);
  }
  return new File(uri).bytesSync();
}

/**
 * Build a real AES-256-GCM package wrapped to THIS device's public key.
 *
 * The BEK is generated locally rather than arriving in a grant, because there is
 * no backend to issue one. Everything downstream of that — the GCM layout, the
 * RSA-OAEP-256 wrap, the licence invariants — is genuine, which is what makes
 * getBook() exercise a real unwrapBek + tag-verified decrypt.
 */
async function buildPackage(bookId: BookId, bytes: Uint8Array): Promise<EncryptedPackage> {
  const fixture = fixtureFor(bookId);

  // Idempotent: reuses the stored keypair rather than orphaning BEKs already
  // wrapped to the old public key.
  const { publicKey } = await generateDeviceKeypair();

  const bek = Uint8Array.from(randomBytes(BEK_BYTES));
  const payload = await encrypt(bytes, bek);
  const wrappedBek = await wrapBek(bek, publicKey);

  /*
    The index, encrypted under the SAME BEK with its OWN nonce — which is what
    src/shared/contracts/search.ts specifies and what contentStore already expects (it persists this
    as `.index.bin` and tracks hasIndex). No change is needed in Encryption or Search for this to work.

    WHICH index is declared per fixture (`searchIndex`) rather than decided by an `if` here, so adding
    a fixture cannot silently inherit another book's — which matters more than it sounds, because
    queryBookIndex THROWS on a bookId mismatch rather than returning nothing.
  */
  const index = fixture.searchIndex
    ? (await encrypt(utf8Encode(JSON.stringify(fixture.searchIndex)), bek)).content
    : undefined;
  // Deliberately the SAME function the real download path uses (downloadManager.ts), not a local
  // sha256 of the PEM text. Both fields below get this one value, so a hand-rolled digest would
  // also satisfy contentStore's licence/encryption fingerprint check — and would mean the one
  // place that check can be rehearsed on-device never exercises the recipe production actually
  // sends. The recipe itself (raw DER, `sha256:` prefix, full hex) is still unconfirmed with
  // wokay — see `src/shared/contracts/CONTRACT_ALIGNMENT.md`, C7.
  const keyFingerprint = await publicKeyFingerprint(publicKey);

  const licence: SignedLicence = {
    licenceId: `dev-licence-${bookId}`,
    // contentStore asserts itemId === bookId and that the two keyFingerprints match.
    itemId: bookId,
    keyFingerprint,
    expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
    // true => Subscription: ciphertext persists and is reopenable offline.
    canPersist: true,
    rights: { print: false },
    // Empty on purpose: contentStore does not verify RS256 yet (only expiry), so
    // a value here would be decorative. When verification lands this fixture must
    // start signing for real, or it will correctly stop loading.
    signature: { alg: 'RS256', kid: 'dev-unverified', value: '' },
  };

  return {
    bookId,
    // THE VALUE getFormat() LATER RETURNS, and therefore what picks the reader's shell
    // and its open command. It is a real field on a real stored package, not a Reader
    // guess — which is the point: this path now rehearses the same routing a downloaded
    // book will use. What it is NOT is a solution to finding B12: this value is only as
    // true as the seed, and a real book still gets whatever `downloadBook()` was passed.
    format: fixture.format,
    content: payload.content, // nonce(12) || ciphertext || tag(16)
    index,
    encryption: {
      algorithm: 'AES-256-GCM',
      layout: 'nonce(12) || ciphertext || tag(16)',
      wrappedBek,
      wrapAlgorithm: 'RSA-OAEP-256',
      keyId: 'dev-master-v1',
      keyFingerprint,
    },
    licence,
    cipherLength: payload.cipherLength,
    originalLength: payload.originalLength,
    mimeType: fixture.mimeType,
  };
}

/**
 * Build a real, UNENCRYPTED audio package — no BEK, no wrap, no `aesGcm` call at all. Audio is
 * NEVER encrypted (primitives.ts, content-provider.ts: "null for open access and ALL audio"), so
 * unlike `buildPackage` above this function imports no crypto material generator; there is none
 * to generate. This is the exact shape `contentStore.test.ts`'s own `openAccessPackage()` test
 * helper builds, and exercises the same branch `decryptBook()` already has and already tests:
 * `if (!pkg.encryption) { // open access / audio: already plaintext }`.
 *
 * OPEN ACCESS, DELIBERATELY, NOT A SUBSCRIPTION/ELITE FIXTURE. The EPUB/PDF fixtures above attach
 * a `licence` with a far-future placeholder `expiresAt`, which is fine for formats where
 * close()/destroy() genuinely gate on a key. For audio, `B15` (CONTRACT_ALIGNMENT.md) is exactly
 * "a persisted audiobook has no real expiry enforcement story yet" — seeding a licensed-looking
 * audio fixture would make that gap read as more solved than it is. `licence: null` is real open
 * access (EncryptedPackage's own doc: "null ⇒ open access"), which sidesteps the question honestly
 * instead of quietly deepening it.
 */
function buildAudioPackage(bookId: BookId, bytes: Uint8Array): EncryptedPackage {
  return {
    bookId,
    format: 'AUDIO',
    content: bytes,
    index: undefined, // search.ts excludes AUDIO from BookSearchIndex.format outright
    encryption: null,
    licence: null,
    cipherLength: bytes.length,
    originalLength: bytes.length,
    mimeType: fixtureFor(bookId).mimeType,
  };
}

/**
 * Bump this whenever the SHAPE of the seeded package changes, so an existing install
 * re-seeds instead of keeping a package built by an older version of this file.
 *
 * 2 — the bundled search index (`EncryptedPackage.index`) was added.
 *
 * WHY THIS EXISTS AT ALL. `isAvailableOffline()` answers "is there ciphertext and a
 * valid key on disk", which is the right question for the reader and the wrong one
 * here: it is true for a package seeded before the index existed, so `ensureSeeded`
 * short-circuited and the index was never written. The symptom is search returning
 * "no matches" forever on any simulator that had run the app once before — correct
 * UI over a stale seed, which is the most expensive kind of wrong to debug.
 *
 * Checking `hasIndex` directly would be the obvious fix and is not available: it lives
 * in ContentStore's private metadata, and the frozen `ContentStore` interface exposes
 * no accessor for it. Adding one is Abhinav's call, and not worth it for scaffolding —
 * a version marker this file owns outright does the same job with no seam change.
 */
const SEED_VERSION = 5;
// 5: TWO DIFFERENT v4s existed before this branch was rebased onto dev_T4 — one that swapped
//    SAMPLE_PDF_MODULE's bytes (Abhinav's, for on-device PDF testing) and one that gave the PDF
//    fixtures their own search index (Reader's, below). Neither is what this file now seeds: the
//    module is back on the generated placeholder AND the index is attached. Staying at 4 would let
//    an install seeded by EITHER v4 short-circuit on isAvailableOffline() and keep a package that
//    matches neither — the 15MB book with no `.index.bin`, or the placeholder under a marker that
//    claims bytes it no longer has. Both fail silently, which is what this counter exists to stop.
// 4: the PDF fixtures gained their own search index. Without this bump an install that had already
//    run the app would short-circuit on isAvailableOffline() and keep a PDF package with no
//    `.index.bin`, so search would go on returning [] and look like the fix had not worked.
// 3: keyFingerprint switched from a local sha256 of the PEM text to publicKeyFingerprint()'s
//    raw-DER digest. Both are self-consistent, so a v2 seed keeps decrypting and nothing breaks
//    without this bump — which is exactly why it is needed: without it, every install that has
//    already run the app short-circuits and never executes the production recipe, defeating the
//    point of calling it here at all.

/** Reader-owned, deliberately NOT in ContentStore's directory — see SEED_VERSION. */
function seedMarker(bookId: BookId): File {
  return new File(Paths.document, `dev-seed-${encodeURIComponent(bookId)}.version`);
}

function seedVersionOnDisk(bookId: BookId): number | null {
  const marker = seedMarker(bookId);
  if (!marker.exists) return null; // seeded before this marker existed → treat as stale
  return Number(marker.textSync());
}

/**
 * Put the sample book into ContentStore if it is not already there, or if what is
 * there was built by an older SEED_VERSION.
 *
 * Seeds only when absent or stale, so the second launch reads what the first
 * persisted — that is the store's offline-reopen path actually being exercised
 * rather than masked by a re-seed every start. A SEED_VERSION bump costs exactly one
 * extra re-seed per install, then the short-circuit resumes.
 *
 * destroy() BEFORE store(), NOT store() alone. Every seed mints a fresh random
 * BEK, and this used to be load-bearing: resolveRawKey() prefers a
 * keychain-cached BEK over unwrapping the package's wrappedBek, so re-seeding
 * on top of a previous seed decrypted the NEW ciphertext with the OLD cached
 * key and failed INTEGRITY_FAILED, permanently. contentStore.store() now
 * invalidates the cache itself when wrappedBek changes
 * (invalidateStaleCachedKeyIfRotated), so that specific trap is closed. The
 * destroy() stays because it does more: it clears orphaned files and the
 * persisted meta from an older SEED_VERSION, which store() alone does not.
 *
 * Deliberately NOT a catch-all retry around a failed read: auto-destroying on
 * any failure would also erase a genuine INTEGRITY_FAILED, which errors.ts
 * requires fail loudly.
 */
export async function ensureSeeded(bookId: BookId): Promise<void> {
  if ((await contentStore.isAvailableOffline(bookId)) && seedVersionOnDisk(bookId) === SEED_VERSION) {
    return;
  }

  await contentStore.destroy(bookId);
  const bytes = await sampleBookBytes(bookId);
  // AUDIO skips buildPackage/aesGcm by default — see buildAudioPackage's own doc comment — unless
  // this specific fixture opts into the encrypted override (DevFixture.audioEncrypted).
  const pkg =
    fixtureFor(bookId).format === 'AUDIO' && !fixtureFor(bookId).audioEncrypted
      ? buildAudioPackage(bookId, bytes)
      : await buildPackage(bookId, bytes);
  await contentStore.store(pkg);
  seedMarker(bookId).write(String(SEED_VERSION));
}
