// Owner: Reader (Ahana).
//
// TEMP: stands in for Encryption/Download's download pass, which is what will
// call ContentStore.store() in production. Without something storing a package
// first, openSession() throws DECRYPTION_FAILED and getBook() can never resolve.
//
// Delete this file when the real download pass lands, then drop the ensureSeeded()
// call in readerAssets.ts.
//
// NOTE assets/reader/sample-plaintext.epub is NO LONGER this file's to delete with
// it — Search's extractor hard-codes that path, so it is now a shared fixture and its
// removal needs Search looped in separately.
//
// What DOES go with this file: the dev search index, which is five items spanning a
// script, an asset and two manifests. The full list is in the header of
// src/features/reader/scripts/buildSampleSearchIndex.ts — read it before deleting,
// or you will leave a dangling script and a stale 360 KB asset behind.

import { Asset } from 'expo-asset';
import { File, Paths } from 'expo-file-system';
import { randomBytes } from 'react-native-quick-crypto';

import { encrypt } from '@/features/encryption/aesGcm';
import { contentStore } from '@/features/encryption/contentStore';
import {
  generateDeviceKeypair,
  publicKeyFingerprint,
  wrapBek,
} from '@/features/encryption/deviceKeypair';
import { utf8Encode } from '@/features/encryption/utf8';
import type { BookId, ContentFormat, EncryptedPackage, SignedLicence } from '@/shared/contracts';

/* eslint-disable-next-line @typescript-eslint/no-require-imports -- Metro asset handle; `.epub` resolves via metro.config.js assetExts. */
const SAMPLE_EPUB_MODULE = require('../../../assets/reader/sample-plaintext.epub') as number;

/**
 * TEMP, with the rest of this file — see the header for the full deletion list.
 *
 * Generated by `npm run reader:build-sample-index`. Required as an object rather than
 * a file read: Metro inlines `.json` at bundle time, so this needs no expo-asset
 * round trip the way the `.epub` above does.
 */
const SAMPLE_SEARCH_INDEX = require('../../../assets/reader/sample-search-index.json') as unknown;

/**
 * TEMP, with the rest of this file. Generated by `npm run reader:build-sample-pdf`.
 *
 * Needs no metro.config.js entry: `.pdf` is already in Expo's default assetExts (only
 * `.epub` had to be added). Resolved through expo-asset exactly like the EPUB.
 */
const SAMPLE_PDF_MODULE = require('../../../assets/reader/sample-plaintext.pdf') as number;

const EPUB_MIME_TYPE = 'application/epub+zip';
const PDF_MIME_TYPE = 'application/pdf';

/** AES-256. Mirrors KEY_BYTES in aesGcm.ts and BEK_BYTES in deviceKeypair.ts. */
const BEK_BYTES = 32;

/**
 * Absolute path to a large EPUB pushed into the app container, used INSTEAD of the bundled 3.6 KB
 * asset when set. Measurement scaffolding for the whole-book work — unset in every normal run.
 *
 * WHY A PATH AND NOT A BUNDLED ASSET: Metro resolves require() statically at bundle time, so a
 * gitignored 20 MB asset is a hard bundling error rather than a soft miss — a "guarded require" is
 * not possible. And a real book must never be committed (T4_Readme.md: never commit real content,
 * encrypted or not). Reading an absolute path sidesteps Metro entirely, which is the same thing
 * sampleBookBytes() already does once expo-asset has resolved a URI.
 *
 * LITERAL MEMBER ACCESS, deliberately — see readerTiming.ts's isTimingEnabled() for why a computed
 * process.env lookup silently never gets inlined.
 *
 * >>> THIS PUTS PLAINTEXT IN THE APP CONTAINER BY CONSTRUCTION. <<< The file is an unencrypted
 * EPUB sitting on disk until it is deleted, which is exactly what a storage-leak sweep should flag.
 * Delete it once the ciphertext is stored and BEFORE running any forensic sweep, or the sweep
 * either reports your own fixture as a leak or "passes" while real content sits in the container.
 */
const FIXTURE_PATH = process.env.EXPO_PUBLIC_READER_FIXTURE_PATH;

/**
 * Which renderer to exercise on this run. `EXPO_PUBLIC_READER_FORMAT=PDF` seeds the sample PDF
 * instead of the sample EPUB, which is the only way to reach the pdf.js path on a device before
 * there is a library screen to pick a real book from.
 *
 * EPUB unless PDF is asked for EXACTLY: anything else — a typo, 'pdf', 'AUDIO' — falls back rather
 * than seeding a book with a format nothing can open. AUDIO is deliberately unreachable here; the
 * reader refuses it with UNSUPPORTED_FORMAT and there is no audio fixture to seed.
 *
 * ORTHOGONAL TO FIXTURE_PATH, which is EPUB-only measurement scaffolding. If both are set,
 * FIXTURE_PATH wins and this is ignored — see DEV_SAMPLE_BOOK_ID below.
 *
 * LITERAL MEMBER ACCESS, deliberately — same reason as FIXTURE_PATH above.
 */
const DEV_FORMAT: ContentFormat = process.env.EXPO_PUBLIC_READER_FORMAT === 'PDF' ? 'PDF' : 'EPUB';

/**
 * A DISTINCT id per fixture, and not cosmetic: ensureSeeded() short-circuits on
 * isAvailableOffline(), so a shared id would find whatever was stored first and never seed the
 * other. With the large EPUB that meant measuring the 3.6 KB book and believing it was 20 MB; with
 * the PDF it would mean `getFormat()` reporting EPUB for a book you asked to be a PDF, and the
 * reader dutifully loading the epub.js shell for it.
 */
export const DEV_SAMPLE_BOOK_ID: BookId = FIXTURE_PATH
  ? 'dev-fixture-epub'
  : DEV_FORMAT === 'PDF'
    ? 'dev-sample-pdf'
    : 'dev-sample-epub';

async function sampleBookBytes(): Promise<Uint8Array> {
  if (FIXTURE_PATH) {
    const fixture = new File(FIXTURE_PATH);
    if (!fixture.exists) {
      throw new Error(
        `EXPO_PUBLIC_READER_FIXTURE_PATH is set to "${FIXTURE_PATH}" but no file is there. ` +
          `Push it into the container first, e.g. cp <book>.epub "$(xcrun simctl get_app_container ` +
          `booted com.taylorandfrancis.tfreader.dev data)/Documents/dev-fixtures/".`
      );
    }
    return fixture.bytesSync();
  }

  const name = DEV_FORMAT === 'PDF' ? 'sample-plaintext.pdf' : 'sample-plaintext.epub';
  const asset = Asset.fromModule(
    DEV_FORMAT === 'PDF' ? SAMPLE_PDF_MODULE : SAMPLE_EPUB_MODULE,
  );

  // Not a network call for a bundled asset, but required: without it `localUri`
  // is null in dev, the classic "works in release, blank in dev" split.
  await asset.downloadAsync();

  const uri = asset.localUri ?? asset.uri;
  if (!uri) {
    throw new Error(`Could not resolve a local URI for ${name}.`);
  }
  return new File(uri).bytesSync();
}

/**
 * Build a real AES-256-GCM package wrapped to THIS device's public key.
 *
 * The BEK is generated locally rather than arriving in a grant, because there is
 * no backend to issue one. Everything downstream of that — the GCM layout, the
 * RSA-OAEP-256 wrap, the licence invariants — is genuine, which is what makes
 * getBook() exercise a real unwrapBek + tag-verified decrypt.
 */
async function buildPackage(bookId: BookId, bytes: Uint8Array): Promise<EncryptedPackage> {
  // Idempotent: reuses the stored keypair rather than orphaning BEKs already
  // wrapped to the old public key.
  const { publicKey } = await generateDeviceKeypair();

  const bek = Uint8Array.from(randomBytes(BEK_BYTES));
  const payload = await encrypt(bytes, bek);
  const wrappedBek = await wrapBek(bek, publicKey);

  /*
    The search index, encrypted under the SAME BEK with its OWN nonce — which is what
    src/shared/contracts/search.ts specifies and what contentStore already expects
    (it persists this as `.index.bin` and tracks hasIndex). No change is needed in
    Encryption or Search for this to work.

    ONLY FOR THE BUNDLED EPUB. With EXPO_PUBLIC_READER_FIXTURE_PATH set the book is
    a different EPUB under a different bookId, and queryBookIndex THROWS when the
    index's bookId is not the one requested. Attaching it there would turn every
    search into an error, against CFIs for the wrong book.

    THE PDF FIXTURE GETS NO INDEX EITHER, for the same reason and one more: the index
    is built from the sample EPUB (its CFIs address that book's spine), and Search's
    extractor is EPUB-only. So a PDF search returns [] — which is honest, and is
    already what every seeded book did before this index existed.
  */
  const index =
    FIXTURE_PATH || DEV_FORMAT === 'PDF'
      ? undefined
      : (await encrypt(utf8Encode(JSON.stringify(SAMPLE_SEARCH_INDEX)), bek)).content;
  // Deliberately the SAME function the real download path uses (downloadManager.ts), not a local
  // sha256 of the PEM text. Both fields below get this one value, so a hand-rolled digest would
  // also satisfy contentStore's licence/encryption fingerprint check — and would mean the one
  // place that check can be rehearsed on-device never exercises the recipe production actually
  // sends. The recipe itself (raw DER, `sha256:` prefix, full hex) is still unconfirmed with
  // wokay — see `src/shared/contracts/CONTRACT_ALIGNMENT.md`, C7.
  const keyFingerprint = await publicKeyFingerprint(publicKey);

  const licence: SignedLicence = {
    licenceId: `dev-licence-${bookId}`,
    // contentStore asserts itemId === bookId and that the two keyFingerprints match.
    itemId: bookId,
    keyFingerprint,
    expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
    // true => Subscription: ciphertext persists and is reopenable offline.
    canPersist: true,
    rights: { print: false },
    // Empty on purpose: contentStore does not verify RS256 yet (only expiry), so
    // a value here would be decorative. When verification lands this fixture must
    // start signing for real, or it will correctly stop loading.
    signature: { alg: 'RS256', kid: 'dev-unverified', value: '' },
  };

  return {
    bookId,
    // THE VALUE getFormat() LATER RETURNS, and therefore what picks the reader's shell
    // and its open command. It is a real field on a real stored package, not a Reader
    // guess — which is the point: this path now rehearses the same routing a downloaded
    // book will use. What it is NOT is a solution to finding B12: this value is only as
    // true as the seed, and a real book still gets whatever `downloadBook()` was passed.
    format: DEV_FORMAT,
    content: payload.content, // nonce(12) || ciphertext || tag(16)
    index,
    encryption: {
      algorithm: 'AES-256-GCM',
      layout: 'nonce(12) || ciphertext || tag(16)',
      wrappedBek,
      wrapAlgorithm: 'RSA-OAEP-256',
      keyId: 'dev-master-v1',
      keyFingerprint,
    },
    licence,
    cipherLength: payload.cipherLength,
    originalLength: payload.originalLength,
    mimeType: DEV_FORMAT === 'PDF' ? PDF_MIME_TYPE : EPUB_MIME_TYPE,
  };
}

/**
 * Bump this whenever the SHAPE of the seeded package changes, so an existing install
 * re-seeds instead of keeping a package built by an older version of this file.
 *
 * 2 — the bundled search index (`EncryptedPackage.index`) was added.
 *
 * WHY THIS EXISTS AT ALL. `isAvailableOffline()` answers "is there ciphertext and a
 * valid key on disk", which is the right question for the reader and the wrong one
 * here: it is true for a package seeded before the index existed, so `ensureSeeded`
 * short-circuited and the index was never written. The symptom is search returning
 * "no matches" forever on any simulator that had run the app once before — correct
 * UI over a stale seed, which is the most expensive kind of wrong to debug.
 *
 * Checking `hasIndex` directly would be the obvious fix and is not available: it lives
 * in ContentStore's private metadata, and the frozen `ContentStore` interface exposes
 * no accessor for it. Adding one is Abhinav's call, and not worth it for scaffolding —
 * a version marker this file owns outright does the same job with no seam change.
 */
const SEED_VERSION = 3;
// 3: keyFingerprint switched from a local sha256 of the PEM text to publicKeyFingerprint()'s
//    raw-DER digest. Both are self-consistent, so a v2 seed keeps decrypting and nothing breaks
//    without this bump — which is exactly why it is needed: without it, every install that has
//    already run the app short-circuits and never executes the production recipe, defeating the
//    point of calling it here at all.

/** Reader-owned, deliberately NOT in ContentStore's directory — see SEED_VERSION. */
function seedMarker(bookId: BookId): File {
  return new File(Paths.document, `dev-seed-${encodeURIComponent(bookId)}.version`);
}

function seedVersionOnDisk(bookId: BookId): number | null {
  const marker = seedMarker(bookId);
  if (!marker.exists) return null; // seeded before this marker existed → treat as stale
  return Number(marker.textSync());
}

/**
 * Put the sample book into ContentStore if it is not already there, or if what is
 * there was built by an older SEED_VERSION.
 *
 * Seeds only when absent or stale, so the second launch reads what the first
 * persisted — that is the store's offline-reopen path actually being exercised
 * rather than masked by a re-seed every start. A SEED_VERSION bump costs exactly one
 * extra re-seed per install, then the short-circuit resumes.
 *
 * destroy() BEFORE store(), NOT store() alone. Every seed mints a fresh random
 * BEK, and this used to be load-bearing: resolveRawKey() prefers a
 * keychain-cached BEK over unwrapping the package's wrappedBek, so re-seeding
 * on top of a previous seed decrypted the NEW ciphertext with the OLD cached
 * key and failed INTEGRITY_FAILED, permanently. contentStore.store() now
 * invalidates the cache itself when wrappedBek changes
 * (invalidateStaleCachedKeyIfRotated), so that specific trap is closed. The
 * destroy() stays because it does more: it clears orphaned files and the
 * persisted meta from an older SEED_VERSION, which store() alone does not.
 *
 * Deliberately NOT a catch-all retry around a failed read: auto-destroying on
 * any failure would also erase a genuine INTEGRITY_FAILED, which errors.ts
 * requires fail loudly.
 */
export async function ensureSeeded(bookId: BookId): Promise<void> {
  if ((await contentStore.isAvailableOffline(bookId)) && seedVersionOnDisk(bookId) === SEED_VERSION) {
    return;
  }

  await contentStore.destroy(bookId);
  await contentStore.store(await buildPackage(bookId, await sampleBookBytes()));
  seedMarker(bookId).write(String(SEED_VERSION));
}
