// Owner: Reader (Ahana).
//
// The ONLY module that knows where the reader's bytes physically come from.
// Everything above it (ReaderWebView, ReaderScreen) deals in "a URI to load" and
// "a base64 string to open" and is deliberately ignorant of the source.
//
// Two assets, both bundled, neither ever fetched from the network:
//   assets/reader/reader.html            generated by `npm run reader:build-html`
//   assets/reader/sample-plaintext.epub  generated by `npm run reader:build-sample`
//
// WHY RELATIVE require() AND NOT AN ALIAS: the alias map (babel.config.js +
// tsconfig paths, which must mirror each other exactly) points `@` at ./src, and
// these live in ./assets, outside it. Adding an `@assets` alias would mean
// editing both halves of that map for two require() calls — the plan explicitly
// ruled out inventing aliases for this task.
//
// WHY require() AT ALL, in a TS file: this is Metro's asset pipeline, not Node
// resolution. `require('....epub')` returns a numeric asset handle that
// expo-asset resolves to a real on-device URI. There is no ESM import form for
// it. `.epub` only resolves because metro.config.js adds it to assetExts;
// `.html` was already a default.

import { Asset } from 'expo-asset';
import { File } from 'expo-file-system';

/* eslint-disable @typescript-eslint/no-require-imports -- Metro asset handles; see header. */
const READER_HTML_MODULE = require('../../../assets/reader/reader.html') as number;
const SAMPLE_EPUB_MODULE = require('../../../assets/reader/sample-plaintext.epub') as number;
/* eslint-enable @typescript-eslint/no-require-imports */

/**
 * Resolve a bundled asset to a local file:// URI.
 *
 * downloadAsync() is required, not optional, and it is not a network call for
 * bundled assets. In a release build the asset is already inside the app and
 * this resolves immediately; in development Metro serves it over the dev-server
 * connection and this copies it into the cache directory. Skipping it leaves
 * `localUri` null in dev, which is the classic "works in release, blank in dev"
 * split.
 */
async function localUriFor(assetModule: number, label: string): Promise<string> {
  const asset = Asset.fromModule(assetModule);
  await asset.downloadAsync();

  const uri = asset.localUri ?? asset.uri;
  if (!uri) {
    throw new Error(`Could not resolve a local URI for ${label}.`);
  }
  return uri;
}

/**
 * file:// URI of the generated, self-contained reader.html to load in the
 * WebView. Self-contained means it makes zero sub-resource requests, which is
 * what lets the WebView be locked down as hard as it is in ReaderWebView.tsx.
 */
export async function getReaderHtmlUri(): Promise<string> {
  return localUriFor(READER_HTML_MODULE, 'reader.html');
}

/**
 * Whole-book bytes for the reader, base64-encoded.
 *
 * >>> THE DECRYPTED-CONTENT SEAM. THIS FUNCTION IS THE ONLY THING THAT CHANGES. <<<
 *
 * Today: reads the bundled PLAINTEXT sample EPUB off disk. No crypto anywhere in
 * this baseline — by design, per the task's constraints.
 *
 * Day 3 / encryption wiring: this becomes, in full —
 *
 *     const bytes = await contentProvider.getBook(bookId);   // Bytes = Uint8Array
 *     return base64FromBytes(bytes);                         // never touches disk
 *
 * (`ContentProvider` / `Bytes` come from '@/shared/contracts' — import the types
 * from the barrel, not by deep path.) Nothing else moves: the WebView already
 * calls `book.open(arrayBuffer, 'binary')` on whatever base64 it is handed, which
 * is the exact call content-provider.ts documents for the EPUB path.
 *
 * TWO CONSTRAINTS THAT MUST SURVIVE THAT SWAP:
 *  1. PLAINTEXT NEVER TOUCHES DISK. Reading a file is fine HERE only because
 *     this sample is already plaintext and already in the bundle. The decrypted
 *     path must go RAM -> base64 -> bridge, never via a temp file.
 *  2. BASE64 OVER injectJavaScript DOES NOT SCALE. It is fine for a 3.6KB
 *     fixture and will not be fine for a ~20MB book — expect to replace the
 *     transport (not this seam) at that point. Known and recorded, not
 *     accidental.
 */
export async function getBookBase64(): Promise<string> {
  const uri = await localUriFor(SAMPLE_EPUB_MODULE, 'sample-plaintext.epub');
  return new File(uri).base64();
}
